import { RARITY, type Joker } from "@/config/types";

export const JOKER_SHEET_URL =
  "https://cdn.jsdelivr.net/gh/Signez/balatro-sprites-i18n@main/dist/en/2x/Jokers.png";

export const JOKERS = [
  { id: "JOKER",                  name: "Joker",                  rarity: RARITY.COMMON,    spriteX: 0,   spriteY: 0,    jokerNumber: 1   },
  { id: "GREEDY_JOKER",           name: "Greedy Joker",           rarity: RARITY.COMMON,    spriteX: 426, spriteY: 95,   jokerNumber: 2   },
  { id: "LUSTY_JOKER",            name: "Lusty Joker",            rarity: RARITY.COMMON,    spriteX: 497, spriteY: 95,   jokerNumber: 3   },
  { id: "WRATHFUL_JOKER",         name: "Wrathful Joker",         rarity: RARITY.COMMON,    spriteX: 568, spriteY: 95,   jokerNumber: 4   },
  { id: "GLUTTONOUS_JOKER",       name: "Gluttonous Joker",       rarity: RARITY.COMMON,    spriteX: 639, spriteY: 95,   jokerNumber: 5   },
  { id: "JOLLY_JOKER",            name: "Jolly Joker",            rarity: RARITY.COMMON,    spriteX: 142, spriteY: 0,    jokerNumber: 6   },
  { id: "ZANY_JOKER",             name: "Zany Joker",             rarity: RARITY.COMMON,    spriteX: 213, spriteY: 0,    jokerNumber: 7   },
  { id: "MAD_JOKER",              name: "Mad Joker",              rarity: RARITY.COMMON,    spriteX: 284, spriteY: 0,    jokerNumber: 8   },
  { id: "CRAZY_JOKER",            name: "Crazy Joker",            rarity: RARITY.COMMON,    spriteX: 355, spriteY: 0,    jokerNumber: 9   },
  { id: "DROLL_JOKER",            name: "Droll Joker",            rarity: RARITY.COMMON,    spriteX: 426, spriteY: 0,    jokerNumber: 10  },
  { id: "SLY_JOKER",              name: "Sly Joker",              rarity: RARITY.COMMON,    spriteX: 0,   spriteY: 1330, jokerNumber: 11  },
  { id: "WILY_JOKER",             name: "Wily Joker",             rarity: RARITY.COMMON,    spriteX: 71,  spriteY: 1330, jokerNumber: 12  },
  { id: "CLEVER_JOKER",           name: "Clever Joker",           rarity: RARITY.COMMON,    spriteX: 142, spriteY: 1330, jokerNumber: 13  },
  { id: "DEVIOUS_JOKER",          name: "Devious Joker",          rarity: RARITY.COMMON,    spriteX: 213, spriteY: 1330, jokerNumber: 14  },
  { id: "CRAFTY_JOKER",           name: "Crafty Joker",           rarity: RARITY.COMMON,    spriteX: 284, spriteY: 1330, jokerNumber: 15  },
  { id: "HALF_JOKER",             name: "Half Joker",             rarity: RARITY.COMMON,    spriteX: 497, spriteY: 0,    jokerNumber: 16  },
  { id: "JOKER_STENCIL",          name: "Joker Stencil",          rarity: RARITY.UNCOMMON,  spriteX: 142, spriteY: 475,  jokerNumber: 17  },
  { id: "FOUR_FINGERS",           name: "Four Fingers",           rarity: RARITY.UNCOMMON,  spriteX: 426, spriteY: 570,  jokerNumber: 18  },
  { id: "MIME",                   name: "Mime",                   rarity: RARITY.UNCOMMON,  spriteX: 284, spriteY: 95,   jokerNumber: 19  },
  { id: "CREDIT_CARD",            name: "Credit Card",            rarity: RARITY.COMMON,    spriteX: 355, spriteY: 95,   jokerNumber: 20  },
  { id: "CEREMONIAL_DAGGER",      name: "Ceremonial Dagger",      rarity: RARITY.UNCOMMON,  spriteX: 355, spriteY: 475,  jokerNumber: 21  },
  { id: "BANNER",                 name: "Banner",                 rarity: RARITY.UNCOMMON,  spriteX: 71,  spriteY: 190,  jokerNumber: 22  },
  { id: "MYSTIC_SUMMIT",          name: "Mystic Summit",          rarity: RARITY.UNCOMMON,  spriteX: 142, spriteY: 190,  jokerNumber: 23  },
  { id: "MARBLE_JOKER",           name: "Marble Joker",           rarity: RARITY.UNCOMMON,  spriteX: 213, spriteY: 190,  jokerNumber: 24  },
  { id: "LOYALTY_CARD",           name: "Loyalty Card",           rarity: RARITY.UNCOMMON,  spriteX: 284, spriteY: 190,  jokerNumber: 25  },
  { id: "EIGHT_BALL",             name: "8 Ball",                 rarity: RARITY.UNCOMMON,  spriteX: 0,   spriteY: 475,  jokerNumber: 26  },
  { id: "MISPRINT",               name: "Misprint",               rarity: RARITY.COMMON,    spriteX: 426, spriteY: 190,  jokerNumber: 27  },
  { id: "DUSK",                   name: "Dusk",                   rarity: RARITY.UNCOMMON,  spriteX: 284, spriteY: 665,  jokerNumber: 28  },
  { id: "RAISED_FIST",            name: "Raised Fist",            rarity: RARITY.COMMON,    spriteX: 568, spriteY: 190,  jokerNumber: 29  },
  { id: "CHAOS_THE_CLOWN",        name: "Chaos the Clown",        rarity: RARITY.COMMON,    spriteX: 71,  spriteY: 0,    jokerNumber: 30  },
  { id: "FIBONACCI",              name: "Fibonacci",              rarity: RARITY.UNCOMMON,  spriteX: 71,  spriteY: 475,  jokerNumber: 31  },
  { id: "STEEL_JOKER",            name: "Steel Joker",            rarity: RARITY.UNCOMMON,  spriteX: 497, spriteY: 190,  jokerNumber: 32  },
  { id: "SCARY_FACE",             name: "Scary Face",             rarity: RARITY.COMMON,    spriteX: 142, spriteY: 285,  jokerNumber: 33  },
  { id: "ABSTRACT_JOKER",         name: "Abstract Joker",         rarity: RARITY.COMMON,    spriteX: 213, spriteY: 285,  jokerNumber: 34  },
  { id: "DELAYED_GRATIFICATION",  name: "Delayed Gratification",  rarity: RARITY.COMMON,    spriteX: 284, spriteY: 285,  jokerNumber: 35  },
  { id: "HACK",                   name: "Hack",                   rarity: RARITY.UNCOMMON,  spriteX: 355, spriteY: 190,  jokerNumber: 36  },
  { id: "PAREIDOLIA",             name: "Pareidolia",             rarity: RARITY.UNCOMMON,  spriteX: 426, spriteY: 285,  jokerNumber: 37  },
  { id: "GROS_MICHEL",            name: "Gros Michel",            rarity: RARITY.UNCOMMON,  spriteX: 497, spriteY: 570,  jokerNumber: 38  },
  { id: "EVEN_STEVEN",            name: "Even Steven",            rarity: RARITY.COMMON,    spriteX: 568, spriteY: 285,  jokerNumber: 39  },
  { id: "ODD_TODD",               name: "Odd Todd",               rarity: RARITY.COMMON,    spriteX: 639, spriteY: 285,  jokerNumber: 40  },
  { id: "SCHOLAR",                name: "Scholar",                rarity: RARITY.COMMON,    spriteX: 0,   spriteY: 380,  jokerNumber: 41  },
  { id: "BUSINESS_CARD",          name: "Business Card",          rarity: RARITY.COMMON,    spriteX: 71,  spriteY: 380,  jokerNumber: 42  },
  { id: "SUPERNOVA",              name: "Supernova",              rarity: RARITY.COMMON,    spriteX: 142, spriteY: 380,  jokerNumber: 43  },
  { id: "RIDE_THE_BUS",           name: "Ride the Bus",           rarity: RARITY.COMMON,    spriteX: 71,  spriteY: 570,  jokerNumber: 44  },
  { id: "SPACE_JOKER",            name: "Space Joker",            rarity: RARITY.UNCOMMON,  spriteX: 213, spriteY: 475,  jokerNumber: 45  },
  { id: "EGG",                    name: "Egg",                    rarity: RARITY.UNCOMMON,  spriteX: 0,   spriteY: 950,  jokerNumber: 46  },
  { id: "BURGLAR",                name: "Burglar",                rarity: RARITY.UNCOMMON,  spriteX: 71,  spriteY: 950,  jokerNumber: 47  },
  { id: "BLACKBOARD",             name: "Blackboard",             rarity: RARITY.UNCOMMON,  spriteX: 142, spriteY: 950,  jokerNumber: 48  },
  { id: "RUNNER",                 name: "Runner",                 rarity: RARITY.COMMON,    spriteX: 213, spriteY: 950,  jokerNumber: 49  },
  { id: "ICE_CREAM",              name: "Ice Cream",              rarity: RARITY.COMMON,    spriteX: 284, spriteY: 950,  jokerNumber: 50  },
  { id: "DNA",                    name: "DNA",                    rarity: RARITY.RARE,      spriteX: 355, spriteY: 950,  jokerNumber: 51  },
  { id: "SPLASH",                 name: "Splash",                 rarity: RARITY.COMMON,    spriteX: 426, spriteY: 950,  jokerNumber: 52  },
  { id: "BLUE_JOKER",             name: "Blue Joker",             rarity: RARITY.COMMON,    spriteX: 497, spriteY: 950,  jokerNumber: 53  },
  { id: "SIX_SENSE",              name: "Six Sense",              rarity: RARITY.UNCOMMON,  spriteX: 568, spriteY: 950,  jokerNumber: 54  },
  { id: "CONSTELLATION",          name: "Constellation",          rarity: RARITY.UNCOMMON,  spriteX: 639, spriteY: 950,  jokerNumber: 55  },
  { id: "HIKER",                  name: "Hiker",                  rarity: RARITY.UNCOMMON,  spriteX: 0,   spriteY: 1045, jokerNumber: 56  },
  { id: "FACELESS",               name: "Faceless",               rarity: RARITY.UNCOMMON,  spriteX: 71,  spriteY: 1045, jokerNumber: 57  },
  { id: "GREEN_JOKER",            name: "Green Joker",            rarity: RARITY.COMMON,    spriteX: 142, spriteY: 1045, jokerNumber: 58  },
  { id: "SUPERPOSITION",          name: "Superposition",          rarity: RARITY.UNCOMMON,  spriteX: 213, spriteY: 1045, jokerNumber: 59  },
  { id: "TO_DO_LIST",             name: "To Do List",             rarity: RARITY.COMMON,    spriteX: 284, spriteY: 1045, jokerNumber: 60  },
  { id: "CAVENDISH",              name: "Cavendish",              rarity: RARITY.UNCOMMON,  spriteX: 355, spriteY: 1045, jokerNumber: 61  },
  { id: "CARD_SHARP",             name: "Card Sharp",             rarity: RARITY.UNCOMMON,  spriteX: 426, spriteY: 1045, jokerNumber: 62  },
  { id: "RED_CARD",               name: "Red Card",               rarity: RARITY.UNCOMMON,  spriteX: 497, spriteY: 1045, jokerNumber: 63  },
  { id: "MADNESS",                name: "Madness",                rarity: RARITY.UNCOMMON,  spriteX: 568, spriteY: 1045, jokerNumber: 64  },
  { id: "SQUARE_JOKER",           name: "Square Joker",           rarity: RARITY.COMMON,    spriteX: 639, spriteY: 1045, jokerNumber: 65  },
  { id: "SEANCE",                 name: "Séance",                 rarity: RARITY.UNCOMMON,  spriteX: 0,   spriteY: 1140, jokerNumber: 66  },
  { id: "RIFF_RAFF",              name: "Riff-raff",              rarity: RARITY.COMMON,    spriteX: 71,  spriteY: 1140, jokerNumber: 67  },
  { id: "VAMPIRE",                name: "Vampire",                rarity: RARITY.UNCOMMON,  spriteX: 142, spriteY: 1140, jokerNumber: 68  },
  { id: "SHORTCUT",               name: "Shortcut",               rarity: RARITY.UNCOMMON,  spriteX: 213, spriteY: 1140, jokerNumber: 69  },
  { id: "HOLOGRAM",               name: "Hologram",               rarity: RARITY.RARE,      spriteX: 284, spriteY: 1140, additionalLayers: [{ spriteX: 142, spriteY: 855 }], jokerNumber: 70  },
  { id: "VAGABOND",               name: "Vagabond",               rarity: RARITY.RARE,      spriteX: 355, spriteY: 1140, jokerNumber: 71  },
  { id: "BARON",                  name: "Baron",                  rarity: RARITY.RARE,      spriteX: 426, spriteY: 1140, jokerNumber: 72  },
  { id: "CLOUD_9",                name: "Cloud 9",                rarity: RARITY.COMMON,    spriteX: 497, spriteY: 1140, jokerNumber: 73  },
  { id: "ROCKET",                 name: "Rocket",                 rarity: RARITY.UNCOMMON,  spriteX: 568, spriteY: 1140, jokerNumber: 74  },
  { id: "OBELISK",                name: "Obelisk",                rarity: RARITY.UNCOMMON,  spriteX: 639, spriteY: 1140, jokerNumber: 75  },
  { id: "MIDAS_MASK",             name: "Midas Mask",             rarity: RARITY.UNCOMMON,  spriteX: 0,   spriteY: 1235, jokerNumber: 76  },
  { id: "LUCHADOR",               name: "Luchador",               rarity: RARITY.UNCOMMON,  spriteX: 71,  spriteY: 1235, jokerNumber: 77  },
  { id: "PHOTOGRAPH",             name: "Photograph",             rarity: RARITY.COMMON,    spriteX: 142, spriteY: 1235, jokerNumber: 78  },
  { id: "GIFT_CARD",              name: "Gift Card",              rarity: RARITY.UNCOMMON,  spriteX: 213, spriteY: 1235, jokerNumber: 79  },
  { id: "TURTLE_BEAN",            name: "Turtle Bean",            rarity: RARITY.UNCOMMON,  spriteX: 284, spriteY: 1235, jokerNumber: 80  },
  { id: "EROSION",                name: "Erosion",                rarity: RARITY.UNCOMMON,  spriteX: 355, spriteY: 1235, jokerNumber: 81  },
  { id: "RESERVED_PARKING",       name: "Reserved Parking",       rarity: RARITY.UNCOMMON,  spriteX: 426, spriteY: 1235, jokerNumber: 82  },
  { id: "MAIL_IN_REBATE",         name: "Mail-In Rebate",         rarity: RARITY.COMMON,    spriteX: 497, spriteY: 1235, jokerNumber: 83  },
  { id: "TO_THE_MOON",            name: "To the Moon",            rarity: RARITY.UNCOMMON,  spriteX: 568, spriteY: 1235, jokerNumber: 84  },
  { id: "HALLUCINATION",          name: "Hallucination",          rarity: RARITY.COMMON,    spriteX: 639, spriteY: 1235, jokerNumber: 85  },
  { id: "FORTUNE_TELLER",         name: "Fortune Teller",         rarity: RARITY.COMMON,    spriteX: 497, spriteY: 475,  jokerNumber: 86  },
  { id: "JUGGLER",                name: "Juggler",                rarity: RARITY.COMMON,    spriteX: 0,   spriteY: 95,   jokerNumber: 87  },
  { id: "DRUNKARD",               name: "Drunkard",               rarity: RARITY.COMMON,    spriteX: 71,  spriteY: 95,   jokerNumber: 88  },
  { id: "STONE_JOKER",            name: "Stone Joker",            rarity: RARITY.UNCOMMON,  spriteX: 639, spriteY: 0,    jokerNumber: 89  },
  { id: "GOLDEN_JOKER",           name: "Golden Joker",           rarity: RARITY.COMMON,    spriteX: 639, spriteY: 190,  jokerNumber: 90  },
  { id: "LUCKY_CAT",              name: "Lucky Cat",              rarity: RARITY.UNCOMMON,  spriteX: 355, spriteY: 1330, jokerNumber: 91  },
  { id: "BASEBALL_CARD",          name: "Baseball Card",          rarity: RARITY.RARE,      spriteX: 426, spriteY: 1330, jokerNumber: 92  },
  { id: "BULL",                   name: "Bull",                   rarity: RARITY.UNCOMMON,  spriteX: 497, spriteY: 1330, jokerNumber: 93  },
  { id: "DIET_COLA",              name: "Diet Cola",              rarity: RARITY.UNCOMMON,  spriteX: 568, spriteY: 1330, jokerNumber: 94  },
  { id: "TRADING_CARD",           name: "Trading Card",           rarity: RARITY.COMMON,    spriteX: 639, spriteY: 1330, jokerNumber: 95  },
  { id: "FLASH_CARD",             name: "Flash Card",             rarity: RARITY.UNCOMMON,  spriteX: 0,   spriteY: 1425, jokerNumber: 96  },
  { id: "POPCORN",                name: "Popcorn",                rarity: RARITY.COMMON,    spriteX: 71,  spriteY: 1425, jokerNumber: 97  },
  { id: "SPARE_TROUSERS",         name: "Spare Trousers",         rarity: RARITY.UNCOMMON,  spriteX: 284, spriteY: 1425, jokerNumber: 98  },
  { id: "ANCIENT_JOKER",          name: "Ancient Joker",          rarity: RARITY.RARE,      spriteX: 497, spriteY: 1425, jokerNumber: 99  },
  { id: "RAMEN",                  name: "Ramen",                  rarity: RARITY.UNCOMMON,  spriteX: 142, spriteY: 1425, jokerNumber: 100 },
  { id: "WALKIE_TALKIE",          name: "Walkie Talkie",          rarity: RARITY.COMMON,    spriteX: 568, spriteY: 1425, jokerNumber: 101 },
  { id: "SELTZER",                name: "Seltzer",                rarity: RARITY.UNCOMMON,  spriteX: 213, spriteY: 1425, jokerNumber: 102 },
  { id: "CASTLE",                 name: "Castle",                 rarity: RARITY.UNCOMMON,  spriteX: 639, spriteY: 1425, jokerNumber: 103 },
  { id: "SMILEY_FACE",            name: "Smiley Face",            rarity: RARITY.COMMON,    spriteX: 426, spriteY: 1425, jokerNumber: 104 },
  { id: "CAMPFIRE",               name: "Campfire",               rarity: RARITY.RARE,      spriteX: 355, spriteY: 1425, jokerNumber: 105 },
  { id: "GOLDEN_TICKET",          name: "Golden Ticket",          rarity: RARITY.UNCOMMON,  spriteX: 355, spriteY: 285,  jokerNumber: 106 },
  { id: "MR_BONES",               name: "Mr. Bones",              rarity: RARITY.RARE,      spriteX: 213, spriteY: 380,  jokerNumber: 107 },
  { id: "ACROBAT",                name: "Acrobat",                rarity: RARITY.UNCOMMON,  spriteX: 142, spriteY: 95,   jokerNumber: 108 },
  { id: "SOCK_AND_BUSKIN",        name: "Sock and Buskin",        rarity: RARITY.UNCOMMON,  spriteX: 213, spriteY: 95,   jokerNumber: 109 },
  { id: "SWASHBUCKLER",           name: "Swashbuckler",           rarity: RARITY.COMMON,    spriteX: 639, spriteY: 475,  jokerNumber: 110 },
  { id: "TROUBADOUR",             name: "Troubadour",             rarity: RARITY.UNCOMMON,  spriteX: 0,   spriteY: 190,  jokerNumber: 111 },
  { id: "CERTIFICATE",            name: "Certificate",            rarity: RARITY.UNCOMMON,  spriteX: 568, spriteY: 760,  jokerNumber: 112 },
  { id: "SMEARED_JOKER",          name: "Smeared Joker",          rarity: RARITY.UNCOMMON,  spriteX: 284, spriteY: 570,  jokerNumber: 113 },
  { id: "THROWBACK",              name: "Throwback",              rarity: RARITY.UNCOMMON,  spriteX: 355, spriteY: 665,  jokerNumber: 114 },
  { id: "HANGING_CHAD",           name: "Hanging Chad",           rarity: RARITY.COMMON,    spriteX: 639, spriteY: 570,  jokerNumber: 115 },
  { id: "ROUGH_GEM",              name: "Rough Gem",              rarity: RARITY.UNCOMMON,  spriteX: 639, spriteY: 665,  jokerNumber: 116 },
  { id: "BLOODSTONE",             name: "Bloodstone",             rarity: RARITY.UNCOMMON,  spriteX: 0,   spriteY: 760,  jokerNumber: 117 },
  { id: "ARROWHEAD",              name: "Arrowhead",              rarity: RARITY.UNCOMMON,  spriteX: 71,  spriteY: 760,  jokerNumber: 118 },
  { id: "ONYX_AGATE",             name: "Onyx Agate",             rarity: RARITY.UNCOMMON,  spriteX: 142, spriteY: 760,  jokerNumber: 119 },
  { id: "GLASS_JOKER",            name: "Glass Joker",            rarity: RARITY.UNCOMMON,  spriteX: 71,  spriteY: 285,  jokerNumber: 120 },
  { id: "SHOWMAN",                name: "Showman",                rarity: RARITY.UNCOMMON,  spriteX: 426, spriteY: 475,  jokerNumber: 121 },
  { id: "FLOWER_POT",             name: "Flower Pot",             rarity: RARITY.UNCOMMON,  spriteX: 0,   spriteY: 570,  jokerNumber: 122 },
  { id: "BLUEPRINT",              name: "Blueprint",              rarity: RARITY.RARE,      spriteX: 0,   spriteY: 285,  jokerNumber: 123 },
  { id: "WEE_JOKER",              name: "Wee Joker",              rarity: RARITY.RARE,      spriteX: 71,  spriteY: 855,  additionalLayers: [{ spriteX: 0, spriteY: 0, scale: 0.6 }], jokerNumber: 124 },
  { id: "MERRY_ANDY",             name: "Merry Andy",             rarity: RARITY.UNCOMMON,  spriteX: 568, spriteY: 0,    jokerNumber: 125 },
  { id: "OOPS_ALL_6S",            name: "Oops! All 6s",           rarity: RARITY.UNCOMMON,  spriteX: 355, spriteY: 570,  jokerNumber: 126 },
  { id: "THE_IDOL",               name: "The Idol",               rarity: RARITY.UNCOMMON,  spriteX: 426, spriteY: 665,  jokerNumber: 127 },
  { id: "SEEING_DOUBLE",          name: "Seeing Double",          rarity: RARITY.UNCOMMON,  spriteX: 284, spriteY: 380,  jokerNumber: 128 },
  { id: "MATADOR",                name: "Matador",                rarity: RARITY.UNCOMMON,  spriteX: 284, spriteY: 475,  jokerNumber: 129 },
  { id: "HIT_THE_ROAD",           name: "Hit the Road",           rarity: RARITY.RARE,      spriteX: 568, spriteY: 475,  jokerNumber: 130 },
  { id: "THE_DUO",                name: "The Duo",                rarity: RARITY.RARE,      spriteX: 355, spriteY: 380,  jokerNumber: 131 },
  { id: "THE_TRIO",               name: "The Trio",               rarity: RARITY.RARE,      spriteX: 426, spriteY: 380,  jokerNumber: 132 },
  { id: "THE_FAMILY",             name: "The Family",             rarity: RARITY.RARE,      spriteX: 497, spriteY: 380,  jokerNumber: 133 },
  { id: "THE_ORDER",              name: "The Order",              rarity: RARITY.RARE,      spriteX: 568, spriteY: 380,  jokerNumber: 134 },
  { id: "THE_TRIBE",              name: "The Tribe",              rarity: RARITY.RARE,      spriteX: 639, spriteY: 380,  jokerNumber: 135 },
  { id: "STUNTMAN",               name: "Stuntman",               rarity: RARITY.UNCOMMON,  spriteX: 568, spriteY: 570,  jokerNumber: 136 },
  { id: "INVISIBLE_JOKER",        name: "Invisible Joker",        rarity: RARITY.RARE,      spriteX: 71,  spriteY: 665,  jokerNumber: 137 },
  { id: "BRAINSTORM",             name: "Brainstorm",             rarity: RARITY.RARE,      spriteX: 497, spriteY: 665,  jokerNumber: 138 },
  { id: "SATELLITE",              name: "Satellite",              rarity: RARITY.UNCOMMON,  spriteX: 568, spriteY: 665,  jokerNumber: 139 },
  { id: "SHOOT_THE_MOON",         name: "Shoot the Moon",         rarity: RARITY.UNCOMMON,  spriteX: 142, spriteY: 570,  jokerNumber: 140 },
  { id: "DRIVERS_LICENSE",        name: "Driver's License",       rarity: RARITY.RARE,      spriteX: 0,   spriteY: 665,  jokerNumber: 141 },
  { id: "CARTOMANCER",            name: "Cartomancer",            rarity: RARITY.RARE,      spriteX: 497, spriteY: 285,  jokerNumber: 142 },
  { id: "ASTRONOMER",             name: "Astronomer",             rarity: RARITY.RARE,      spriteX: 142, spriteY: 665,  jokerNumber: 143 },
  { id: "BURNT_JOKER",            name: "Burnt Joker",            rarity: RARITY.UNCOMMON,  spriteX: 213, spriteY: 665,  jokerNumber: 144 },
  { id: "BOOTSTRAPS",             name: "Bootstraps",             rarity: RARITY.UNCOMMON,  spriteX: 639, spriteY: 760,  jokerNumber: 145 },
  { id: "CANIO",                  name: "Canio",                  rarity: RARITY.LEGENDARY, spriteX: 213, spriteY: 760,  additionalLayers: [{ spriteX: 213, spriteY: 855 }], jokerNumber: 146 },
  { id: "TRIBOULET",              name: "Triboulet",              rarity: RARITY.LEGENDARY, spriteX: 284, spriteY: 760,  additionalLayers: [{ spriteX: 284, spriteY: 855 }], jokerNumber: 147 },
  { id: "YORICK",                 name: "Yorick",                 rarity: RARITY.LEGENDARY, spriteX: 355, spriteY: 760,  additionalLayers: [{ spriteX: 355, spriteY: 855 }], jokerNumber: 148 },
  { id: "CHICOT",                 name: "Chicot",                 rarity: RARITY.LEGENDARY, spriteX: 426, spriteY: 760,  additionalLayers: [{ spriteX: 426, spriteY: 855 }], jokerNumber: 149 },
  { id: "PERKEO",                 name: "Perkeo",                 rarity: RARITY.LEGENDARY, spriteX: 497, spriteY: 760,  additionalLayers: [{ spriteX: 497, spriteY: 855 }], jokerNumber: 150 },
  { id: "LOCKED_JOKER",           name: "Locked Joker",           rarity: RARITY.COMMON,    spriteX: 568, spriteY: 855  },
] as const satisfies ReadonlyArray<Joker>;

export type JokerId = (typeof JOKERS)[number]["id"];
