import type { Meta, StoryObj } from "@storybook/react";

// ── Scale data (generated by scripts/generate-palette.ts) ────────────────────

const STEPS = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950] as const;
type Step = (typeof STEPS)[number];

type Scale = {
  name: string;
  canonical: Step;
  steps: Record<Step, string>;
};

const RARITY: Scale[] = [
  {
    name: "Common",
    canonical: 400,
    steps: {
      50: "#f6f6f8", 100: "#ebebed", 200: "#d7d7da", 300: "#c3c3c9",
      400: "#aaaab2", 500: "#8b8b93", 600: "#6e6e74", 700: "#525256",
      800: "#38383b", 900: "#1f1f22", 950: "#0e0e11",
    },
  },
  {
    name: "Uncommon",
    canonical: 400,
    steps: {
      50: "#ebf8ff", 100: "#e0edfd", 200: "#c1dafa", 300: "#9fc7fb",
      400: "#70aefa", 500: "#548ed6", 600: "#4571a7", 700: "#36547a",
      800: "#233955", 900: "#0a203a", 950: "#000e26",
    },
  },
  {
    name: "Rare",
    canonical: 400,
    steps: {
      50: "#ffefee", 100: "#ffe4e2", 200: "#fdc9c6", 300: "#fdaba7",
      400: "#fa8180", 500: "#d66363", 600: "#a75150", 700: "#7a3e3d",
      800: "#552928", 900: "#390f10", 950: "#240002",
    },
  },
  {
    name: "Legendary",
    canonical: 200,
    steps: {
      50: "#fef7e0", 100: "#f8ebc4", 200: "#fad45b", 300: "#eabf1b",
      400: "#cba722", 500: "#a68925", 600: "#826d25", 700: "#605121",
      800: "#453600", 900: "#2b1d00", 950: "#190b00",
    },
  },
];

const STAKE: Scale[] = [
  {
    name: "White",
    canonical: 100,
    steps: {
      50: "#f7f7f7", 100: "#ebebeb", 200: "#d7d7d7", 300: "#c4c4c4",
      400: "#ababab", 500: "#8c8c8c", 600: "#6f6f6f", 700: "#525252",
      800: "#383838", 900: "#1f1f1f", 950: "#0e0e0e",
    },
  },
  {
    name: "Red",
    canonical: 600,
    steps: {
      50: "#ffeee9", 100: "#ffe3de", 200: "#f4cdc7", 300: "#f0b3aa",
      400: "#e98f84", 500: "#dc5f54", 600: "#c92222", 700: "#932420",
      800: "#5f201b", 900: "#3e0907", 950: "#280000",
    },
  },
  {
    name: "Green",
    canonical: 500,
    steps: {
      50: "#ebfcec", 100: "#e0f1e0", 200: "#c8dfc8", 300: "#aad0ac",
      400: "#82bc86", 500: "#4ba256", 600: "#30823c", 700: "#296030",
      800: "#214024", 900: "#07270c", 950: "#001500",
    },
  },
  {
    name: "Black",
    canonical: 700,
    steps: {
      50: "#f7f7f7", 100: "#ebebeb", 200: "#d7d7d7", 300: "#c4c4c4",
      400: "#ababab", 500: "#8c8c8c", 600: "#6f6f6f", 700: "#525252",
      800: "#383838", 900: "#1f1f1f", 950: "#0e0e0e",
    },
  },
  {
    name: "Blue",
    canonical: 500,
    steps: {
      50: "#e9f9ff", 100: "#ddedfe", 200: "#c3daf2", 300: "#a3c8ee",
      400: "#77b0e9", 500: "#3991e0", 600: "#2372b7", 700: "#225585",
      800: "#1c3a57", 900: "#02203b", 950: "#000e28",
    },
  },
  {
    name: "Purple",
    canonical: 600,
    steps: {
      50: "#faf2ff", 100: "#eee7fe", 200: "#dbd3ed", 300: "#c9bce6",
      400: "#b39edc", 500: "#9879cf", 600: "#7f51c0", 700: "#603a95",
      800: "#402b60", 900: "#25153c", 950: "#140428",
    },
  },
  {
    name: "Orange",
    canonical: 500,
    steps: {
      50: "#fff1e9", 100: "#fde5dd", 200: "#f3cec2", 300: "#efb4a0",
      400: "#e79274", 500: "#d8653c", 600: "#a95233", 700: "#7c3f2a",
      800: "#532c1e", 900: "#371206", 950: "#230200",
    },
  },
  {
    name: "Gold",
    canonical: 400,
    steps: {
      50: "#fff3e2", 100: "#fbe7d7", 200: "#fccda6", 300: "#fcb270",
      400: "#f48e0c", 500: "#c7761a", 600: "#9b5e1f", 700: "#72471e",
      800: "#512f0b", 900: "#351500", 950: "#210400",
    },
  },
];

// ── Components ────────────────────────────────────────────────────────────────

const SWATCH_W = 64;
const SWATCH_H = 48;
const LABEL_W = 40;
const GAP = 2;

const RotatedLabel = ({ text, dark }: { text: string; dark: boolean }) => (
  <div
    aria-hidden="true"
    style={{
      width: LABEL_W,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
    }}
  >
    <span
      style={{
        writingMode: "vertical-rl",
        transform: "rotate(180deg)",
        fontSize: 9,
        fontFamily: "monospace",
        letterSpacing: "0.15em",
        textTransform: "uppercase",
        color: dark ? "#52525b" : "#a1a1aa",
        userSelect: "none",
      }}
    >
      {text}
    </span>
  </div>
);

const SwatchStrip = ({
  scale,
  bg,
  label,
}: {
  scale: Scale;
  bg: string;
  label: string;
}) => {
  const dark = bg === "#09090b";
  const labelColor = dark ? "#a1a1aa" : "#71717a";
  return (
    <div
      style={{
        display: "flex",
        alignItems: "flex-start",
        background: bg,
        borderRadius: 8,
        padding: "10px 12px",
      }}
    >
      <RotatedLabel text={label} dark={dark} />
      <div style={{ display: "flex", flexDirection: "column", gap: 4 }}>
        {/* Step number headers */}
        <div style={{ display: "flex", gap: GAP }} aria-hidden="true">
          {STEPS.map((step) => (
            <div
              key={step}
              style={{
                width: SWATCH_W,
                textAlign: "center",
                fontSize: 10,
                fontFamily: "monospace",
                color: labelColor,
                userSelect: "none",
              }}
            >
              {step}
            </div>
          ))}
        </div>
        <div style={{ display: "flex", gap: GAP }}>
        {STEPS.map((step) => {
          const isCanonical = step === scale.canonical;
          return (
            <div
              key={step}
              style={{
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                gap: 6,
              }}
            >
              <div
                title={`${scale.name} ${step}: ${scale.steps[step]}`}
                style={{
                  width: SWATCH_W,
                  height: SWATCH_H,
                  borderRadius: 4,
                  background: scale.steps[step],
                  outline: isCanonical ? "2px solid #FA9108" : undefined,
                  outlineOffset: isCanonical ? 2 : undefined,
                  flexShrink: 0,
                }}
              />
              {/* Hex value — only shown for canonical */}
              <span
                style={{
                  fontSize: 9,
                  fontFamily: "monospace",
                  color: dark ? "#52525b" : "#a1a1aa",
                  opacity: isCanonical ? 1 : 0,
                  userSelect: "none",
                  letterSpacing: "0.02em",
                }}
                aria-hidden="true"
              >
                {scale.steps[step]}
              </span>
            </div>
          );
        })}
        </div>
      </div>
    </div>
  );
};


const ColorScaleBlock = ({ scale }: { scale: Scale }) => (
  <div style={{ display: "flex", flexDirection: "column", gap: 4 }}>
    <div style={{ display: "flex", alignItems: "baseline", gap: 10, marginBottom: 4 }}>
      <h3
        style={{
          margin: 0,
          fontSize: 14,
          fontWeight: 600,
          color: "#ffffff",
          fontFamily: "sans-serif",
        }}
      >
        {scale.name}
      </h3>
      <span
        style={{
          fontSize: 11,
          fontFamily: "monospace",
          color: "#d4d4d8",
        }}
      >
        canonical: {scale.canonical} · {scale.steps[scale.canonical]}
      </span>
    </div>
    <SwatchStrip scale={scale} bg="#ffffff" label="Light" />
    <SwatchStrip scale={scale} bg="#09090b" label="Dark" />
  </div>
);

const Divider = ({ label }: { label: string }) => (
  <div
    style={{
      display: "flex",
      alignItems: "center",
      gap: 12,
      marginTop: 8,
    }}
  >
    <span
      style={{
        fontSize: 11,
        fontFamily: "monospace",
        textTransform: "uppercase",
        letterSpacing: "0.12em",
        color: "#d4d4d8",
        whiteSpace: "nowrap",
      }}
    >
      {label}
    </span>
    <div style={{ height: 1, background: "#52525b", flex: 1 }} />
  </div>
);

const BasePaletteView = () => (
  <div
    style={{
      background: "#71717a",
      minHeight: "100vh",
      padding: "40px 48px",
      display: "flex",
      flexDirection: "column",
      gap: 32,
      fontFamily: "sans-serif",
    }}
  >
    <div>
      <p
        style={{
          margin: 0,
          fontSize: 11,
          fontFamily: "monospace",
          textTransform: "uppercase",
          letterSpacing: "0.12em",
          color: "#d4d4d8",
        }}
      >
        Design Tokens
      </p>
      <h1 style={{ margin: "4px 0 0", fontSize: 28, fontWeight: 700, color: "#ffffff" }}>
        Color Scales
      </h1>
      <p style={{ margin: "8px 0 0", fontSize: 13, color: "#e4e4e7", maxWidth: 520 }}>
        OKLCH-generated 11-step scales for each game color. The{" "}
        <span style={{ color: "#FA9108" }}>gold ring</span> marks the canonical
        game color within each scale. Swatches are shown on both white and dark
        surfaces.
      </p>
    </div>

    <Divider label="Rarity" />
    {RARITY.map((scale) => (
      <ColorScaleBlock key={scale.name} scale={scale} />
    ))}

    <Divider label="Stake" />
    {STAKE.map((scale) => (
      <ColorScaleBlock key={scale.name} scale={scale} />
    ))}
  </div>
);

// ── Story ─────────────────────────────────────────────────────────────────────

const meta: Meta = {
  title: "Design Tokens/Color Scales",
  parameters: {
    layout: "fullscreen",
    a11y: { disable: true },
  },
};

export default meta;
type Story = StoryObj;

export const BasePalette: Story = {
  render: () => <BasePaletteView />,
};
